name: app
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.8
  - pip:
    - dash
    - dash-renderer
    - dash-core-components
    - dash-html-components
    - plotly
    - gunicorn 
